name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
